wandb_version: 1

activation:
  value: relu
alpha:
  value: 0.003787885987760984
batch_size:
  value: 16
early_stopping:
  value: true
hidden_layer_sizes:
  value:
  - 64
  - 32
learning_rate:
  value: 0.0566635056580585
max_iter:
  value: 1000
patience:
  value: 20
validation_split:
  value: 0.2
