wandb_version: 1

activation:
  value: relu
alpha:
  value: 0.003719569734407519
batch_size:
  value: 32
early_stopping:
  value: true
hidden_layer_sizes:
  value:
  - 32
  - 16
learning_rate:
  value: 0.05139767886902541
max_iter:
  value: 1000
patience:
  value: 20
validation_split:
  value: 0.2
