wandb_version: 1

activation:
  value: tanh
alpha:
  value: 0.0030129021054858744
batch_size:
  value: 16
early_stopping:
  value: true
hidden_layer_sizes:
  value:
  - 32
  - 16
learning_rate:
  value: 0.08742106927462194
max_iter:
  value: 1000
patience:
  value: 20
validation_split:
  value: 0.2
