wandb_version: 1

activation:
  value: tanh
alpha:
  value: 0.007869981693182359
batch_size:
  value: 64
early_stopping:
  value: true
hidden_layer_sizes:
  value:
  - 32
learning_rate:
  value: 0.02234606318172864
max_iter:
  value: 1000
patience:
  value: 20
validation_split:
  value: 0.2
