_wandb:
    value:
        cli_version: 0.18.3
        m: []
        python_version: 3.12.7
        t:
            "1":
                - 5
                - 53
                - 55
            "2":
                - 5
                - 53
                - 55
            "3":
                - 2
                - 23
                - 55
            "4": 3.12.7
            "5": 0.18.3
            "8":
                - 5
            "12": 0.18.3
            "13": darwin-arm64
activation:
    value: sigmoid
alpha:
    value: 0.01
batch_size:
    value: 64
early_stopping:
    value: true
hidden_layer_sizes:
    value:
        - 128
        - 64
        - 32
learning_rate:
    value: 0.1
max_iter:
    value: 1000
patience:
    value: 20
validation_split:
    value: 0.2
